apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-trivy-app
  namespace: argocd   
spec:
  project: default

  source:
    repoURL: 'git@github.com:AhmedAmrgg/simple-gitops.git'   
    targetRevision: main
    path: app-1   

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:   
      prune: true
      selfHeal: true
