apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd   
spec:
  project: default
  source:
    repoURL: 'git@github.com:AhmedAmrgg/simple-gitops.git'   
    targetRevision: main
    path: infrastructure 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:   
      prune: true
      selfHeal: true
